module.exports = {
  SEND_GCPPDF_DATA: "SEND_GCPPDF_DATA",
  SEND_GCPTAR_DATA: "SEND_GCPTAR_DATA",
  SEND_60TAR_DATA: "SEND_60TAR_DATA",
  SEND_APIURL_DATA: "SEND_APIURL_DATA",
  SEND_COMBINATION_TOOL: "SEND_COMBINATION_TOOL",
  SEND_COLLECTION_TOOL: "SEND_COLLECTION_TOOL",
  SEND_BEFORE_EXCEL: "SEND_EXCEL_BEFORE",
  SEND_AFTER_EXCEL: "SEND_EXCEL_AFTER",
};
